In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [ ]:
seed_split = np.load(file="../seed_for_dataSplit.npy")
seed_inital = np.load(file="../seed_for_initialSamples.npy")
seed_model = np.load(file="../seed_for_model.npy")

In [3]:
# loading the dataset
df = pd.read_csv("../datasets/Graphene_Periodic/Graphene_Oxide_Dataset.csv")

In [4]:
df

,file_name,C,H,O,atom_number_total,C_concentration,H_concentration,O_concentration,defects_count,defects_concentration,...,norm_density_ether_std,norm_density_hydro_std,norm_density_O_skew,norm_density_ether_skew,norm_density_hydro_skew,norm_density_O_kurt,norm_density_ether_kurt,norm_density_hydro_kurt,total_energy,Fermi_energy
0,bulk_1,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,...,0.043604,0.034117,0.869206,1.007559,1.812119,0.379164,0.571045,3.364866,-41472.7339,-5.1013
1,bulk_2,720,30,80,830,0.867470,0.036145,0.096385,2,0.002778,...,0.041886,0.030641,0.572613,0.806199,1.447266,-0.146294,-0.020450,1.607799,-41468.1275,-5.1348
2,bulk_3,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,...,0.042229,0.033057,0.518967,0.814323,1.896532,-0.319127,-0.164948,3.993506,-41466.7847,-5.1369
3,bulk_4,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,...,0.041169,0.030938,0.623595,0.829075,1.431133,0.057108,-0.142851,1.537485,-41469.8110,-5.0970
4,bulk_5,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,...,0.049669,0.030094,0.650626,1.016273,1.529611,-0.406791,0.266515,2.132375,-41471.9441,-5.1060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,bulk_1613,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,...,0.032703,0.039776,0.692315,1.668770,1.196665,-0.096386,2.388201,0.958527,-41256.0683,-4.9582
1613,bulk_1614,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,...,0.029262,0.038867,0.721035,1.397469,1.239953,0.126708,1.395016,1.427410,-41258.9494,-4.9408
1614,bulk_1615,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,...,0.031167,0.039185,0.713733,1.522324,1.184583,0.011947,1.913812,1.200657,-41256.1453,-4.9772
1615,bulk_1616,720,50,75,845,0.852071,0.059172,0.088757,4,0.005556,...,0.032872,0.046005,1.077987,1.817385,1.592448,0.747327,3.580019,2.535325,-41257.8300,-4.9577
1616,bulk_1617,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,...,0.030955,0.044516,0.819208,1.577382,1.371901,0.487985,2.046434,1.873707,-41257.3906,-4.9385

In [5]:
df = df.drop(['file_name'], axis=1)
print(df[df.duplicated(keep=False)])

Empty DataFrame
Columns: [C, H, O, atom_number_total, C_concentration, H_concentration, O_concentration, defects_count, defects_concentration, max_oop, mae_oop, std_oop, rmse_oop, residual_oop, ether_count, hydroxyl_count, carboxyl_count, all_agent_group_count, ether_concentration, hydroxyl_concentration, carboxyl_concentration, def_local_ether_count, def_local_hydroxyl_count, def_local_carboxyl_count, def_local_other_count, max_bond_angle (deg), max_bond_length (nm), mass_density_, particle_density, C-C:total_number, C-C:mean_value, C-C:error, C-C_sp1-sp2:total_number, C-C_sp1-sp2:mean_value, C-C_sp1-sp2:error, C-C_sp1-sp3:total_number, C-C_sp1-sp3:mean_value, C-C_sp1-sp3:error, C-C_sp2-sp2:total_number, C-C_sp2-sp2:mean_value, C-C_sp2-sp2:error, C-C_sp2-sp3:total_number, C-C_sp2-sp3:mean_value, C-C_sp2-sp3:error, C-C_sp2-strained:total_number, C-C_sp2-strained:mean_value, C-C_sp2-strained:error, C-C_sp3-sp3:total_number, C-C_sp3-sp3:mean_value, C-C_sp3-sp3:error, C-C_sp3-strained:total_number, C-C_sp3-strained:mean_value, C-C_sp3-strained:error, C-C-C:total_number, C-C-C:mean_value, C-C-C:error, C-C-C_C-sp1-C:total_number, C-C-C_C-sp1-C:mean_value, C-C-C_C-sp1-C:error, C-C-C_C-sp2-C:total_number, C-C-C_C-sp2-C:mean_value, C-C-C_C-sp2-C:error, C-C-C_C-sp3-C:total_number, C-C-C_C-sp3-C:mean_value, C-C-C_C-sp3-C:error, C-C-C_C-strained-C:total_number, C-C-C_C-strained-C:mean_value, C-C-C_C-strained-C:error, C-C-O:total_number, C-C-O:mean_value, C-C-O:error, C-C-O_C-sp1-O:total_number, C-C-O_C-sp1-O:mean_value, C-C-O_C-sp1-O:error, C-C-O_C-sp2-O:total_number, C-C-O_C-sp2-O:mean_value, C-C-O_C-sp2-O:error, C-C-O_C-sp3-O:total_number, C-C-O_C-sp3-O:mean_value, C-C-O_C-sp3-O:error, C-C-O_C-strained-O:total_number, C-C-O_C-strained-O:mean_value, C-C-O_C-strained-O:error, C-O:total_number, C-O:mean_value, C-O:error, C-O_sp1-sp1:total_number, C-O_sp1-sp1:mean_value, C-O_sp1-sp1:error, C-O_sp1-strained:total_number, C-O_sp1-strained:mean_value, C-O_sp1-strained:error, C-O_sp2-sp1:total_number, C-O_sp2-sp1:mean_value, C-O_sp2-sp1:error, C-O_sp2-strained:total_number, C-O_sp2-strained:mean_value, C-O_sp2-strained:error, C-O_sp3-sp1:total_number, C-O_sp3-sp1:mean_value, ...]
Index: []

[0 rows x 503 columns]

In [6]:
df = df.dropna(axis=1)
df

,C,H,O,atom_number_total,C_concentration,H_concentration,O_concentration,defects_count,defects_concentration,max_oop,...,norm_density_ether_std,norm_density_hydro_std,norm_density_O_skew,norm_density_ether_skew,norm_density_hydro_skew,norm_density_O_kurt,norm_density_ether_kurt,norm_density_hydro_kurt,total_energy,Fermi_energy
0,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,2.329913,...,0.043604,0.034117,0.869206,1.007559,1.812119,0.379164,0.571045,3.364866,-41472.7339,-5.1013
1,720,30,80,830,0.867470,0.036145,0.096385,2,0.002778,2.194026,...,0.041886,0.030641,0.572613,0.806199,1.447266,-0.146294,-0.020450,1.607799,-41468.1275,-5.1348
2,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,2.563249,...,0.042229,0.033057,0.518967,0.814323,1.896532,-0.319127,-0.164948,3.993506,-41466.7847,-5.1369
3,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,2.187304,...,0.041169,0.030938,0.623595,0.829075,1.431133,0.057108,-0.142851,1.537485,-41469.8110,-5.0970
4,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,1.893008,...,0.049669,0.030094,0.650626,1.016273,1.529611,-0.406791,0.266515,2.132375,-41471.9441,-5.1060
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,2.308300,...,0.032703,0.039776,0.692315,1.668770,1.196665,-0.096386,2.388201,0.958527,-41256.0683,-4.9582
1613,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,1.807178,...,0.029262,0.038867,0.721035,1.397469,1.239953,0.126708,1.395016,1.427410,-41258.9494,-4.9408
1614,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,1.944294,...,0.031167,0.039185,0.713733,1.522324,1.184583,0.011947,1.913812,1.200657,-41256.1453,-4.9772
1615,720,50,75,845,0.852071,0.059172,0.088757,4,0.005556,1.781176,...,0.032872,0.046005,1.077987,1.817385,1.592448,0.747327,3.580019,2.535325,-41257.8300,-4.9577
1616,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,2.098948,...,0.030955,0.044516,0.819208,1.577382,1.371901,0.487985,2.046434,1.873707,-41257.3906,-4.9385

In [7]:
df2 = df.groupby(['C', 'H', 'O']).size().reset_index().rename(columns={0:'count'})
df2

      C    H    O  count
0   720   25   50     99
1   720   25   75    100
2   720   30   80     98
3   720   30  160     96
4   720   40  100     99
5   720   50   75     96
6   720   50  100    100
7   720   50  150     84
8   720   70  110     91
9   720   70  130     92
10  720   75  150     97
11  720   80  190     84
12  720   90  120     94
13  720   90  150     32
14  720  100  150     77
15  720  100  200     77
16  720  100  230     59
17  720  120  290     46
18  720  140  260     69
19  720  170  290     27

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns
# Create the plot
font = {'family': 'monospace', 'size': 16, 'weight':'bold'}
plt.rc('font', **font)
plt.rcParams['font.family'] = 'monospace'

sns.set_style("whitegrid")
plt.figure(figsize=(6, 5), dpi=300)

sns.histplot(data=df2, x='count', kde=True, color='#cdb4db', edgecolor='#e5e5e5',bins=20)

plt.title('Graphene Oxide Nanoflake', fontsize=20, fontname="monospace",weight='bold')
plt.xlabel('Data Group Size', fontsize=18, fontname="monospace", weight='bold')
plt.ylabel('Count', fontsize=18, fontname="monospace", weight='bold')

# Show the plot
plt.tight_layout()
plt.savefig('Graphene_hist.png',
               bbox_inches="tight",
               pad_inches=0.05)
plt.show()

In [ ]:
# Drop the labels
df_subset = df.drop(['total_energy', 'Fermi_energy'], axis=1)
df_subset

,C,H,O,atom_number_total,C_concentration,H_concentration,O_concentration,defects_count,defects_concentration,max_oop,...,norm_density_hydro_max,norm_density_O_std,norm_density_ether_std,norm_density_hydro_std,norm_density_O_skew,norm_density_ether_skew,norm_density_hydro_skew,norm_density_O_kurt,norm_density_ether_kurt,norm_density_hydro_kurt
0,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,2.329913,...,0.195072,0.056767,0.043604,0.034117,0.869206,1.007559,1.812119,0.379164,0.571045,3.364866
1,720,30,80,830,0.867470,0.036145,0.096385,2,0.002778,2.194026,...,0.155042,0.051838,0.041886,0.030641,0.572613,0.806199,1.447266,-0.146294,-0.020450,1.607799
2,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,2.563249,...,0.207937,0.048658,0.042229,0.033057,0.518967,0.814323,1.896532,-0.319127,-0.164948,3.993506
3,720,30,80,830,0.867470,0.036145,0.096385,4,0.005556,2.187304,...,0.152699,0.048577,0.041169,0.030938,0.623595,0.829075,1.431133,0.057108,-0.142851,1.537485
4,720,30,80,830,0.867470,0.036145,0.096385,6,0.008333,1.893008,...,0.156798,0.058811,0.049669,0.030094,0.650626,1.016273,1.529611,-0.406791,0.266515,2.132375
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1612,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,2.308300,...,0.197112,0.046641,0.032703,0.039776,0.692315,1.668770,1.196665,-0.096386,2.388201,0.958527
1613,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,1.807178,...,0.199033,0.045994,0.029262,0.038867,0.721035,1.397469,1.239953,0.126708,1.395016,1.427410
1614,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,1.944294,...,0.199988,0.046979,0.031167,0.039185,0.713733,1.522324,1.184583,0.011947,1.913812,1.200657
1615,720,50,75,845,0.852071,0.059172,0.088757,4,0.005556,1.781176,...,0.260628,0.055520,0.032872,0.046005,1.077987,1.817385,1.592448,0.747327,3.580019,2.535325
1616,720,50,75,845,0.852071,0.059172,0.088757,0,0.000000,2.098948,...,0.256751,0.048988,0.030955,0.044516,0.819208,1.577382,1.371901,0.487985,2.046434,1.873707

In [ ]:
data = df_subset
labels_true = df[['Fermi_energy']]

for i in range(20):
    X_train, X_test, y_train, y_test = train_test_split(data, labels_true, test_size=0.3, random_state=seed_split[i])
    
    scaler = preprocessing.StandardScaler()
    X_train[X_train.columns] = scaler.fit_transform(X_train[X_train.columns])
    X_test[X_test.columns] = scaler.transform(X_test[X_test.columns])
    
    X_train.to_csv("../datasets/Graphene_Periodic/split_data//X_train" + str(i) +".csv", encoding='utf-8', index=False)
    X_test.to_csv("../datasets/Graphene_Periodic/split_data//X_test" + str(i) +".csv", encoding='utf-8', index=False)
    y_train.to_csv("../datasets/Graphene_Periodic/split_data//y_train" + str(i) +".csv", encoding='utf-8', index=False)
    y_test.to_csv("../datasets/Graphene_Periodic/split_data//y_test" + str(i) +".csv", encoding='utf-8', index=False)